### PR TITLE
Add Simplified Chinese translation resources

### PR DESCRIPTION
**Pull request by wcxu21**
Hi, I'm from China
Suddenly found this open source project, it is very convenient for video processing.
I added simplified Chinese translation resources, can you include simplified Chinese in future versions.
I have participated in the Chinese translation of multiple open source projects. If you are willing to add Chinese translation, I will continue to participate in the project translation in future versions.
Thanks for your work.

### CODE REVIEW

**Comment by philipbutkiewicz** [comment]
Hello,

Thank you for your hard work!
Please let me have a few days to review the translations. :)

**Comment by wcxu21** [comment]
> Hello,
> 
> Thank you for your hard work! Please let me have a few days to review the translations. :)

Here are some suggestions for multi-language.

Since the current language resources are too scattered, if you want to add multiple languages ​​in the future, you will need a lot of resource files.

Can you try to call the language in the form of character text loading, so that it can be well managed even if there are multiple languages.

Language examples: Chinese.lng, English.lng, or other suffixes that can be edited more easily.

**Comment by philipbutkiewicz** [comment]
Localization via resources is a standard way of localizing .NET applications (see https://learn.microsoft.com/en-us/dotnet/core/extensions/localization).
You can use external tools like [Zeta Resource Editor](https://github.com/UweKeim/ZetaResourceEditor) to make translating .NET applications a little bit easier.

**Comment by philipbutkiewicz** [comment]
All of this is true of SharpCut 1.x, however. When I have some more free time I will continue working on SharpCut 2 in C.

**Review by philipbutkiewicz — APPROVED** [review]

**Pull request merged**
